### ISSUE TITLE
sql includes SELECT P0."id"

### ISSUE THREAD

**Issue by ssomnoremac** [absinthe-graphql/absinthe_example#11]
[Running a phoenix/absinthe test app](https://github.com/ssomnoremac/blog_phoenix/tree/cameron) following this guide with mssql-ecto and for some reason it's asking the db for the `id` field. 

I'm wondering why sql statement includes it along with other fields not in the graphql query. `id` isn't a column, just like in your example. Primary keys are `sm_id` in my case. 

```
[debug] GraphQL Document:
query{
  profiles{
    firstName
  }
}
[debug] QUERY ERROR source="Profile" db=137.5ms
SELECT P0."id", P0."sm_id", P0."first_name" FROM "Profile" AS P0 []
[info] Sent 500 in 271ms
[error] #PID<0.408.0> running BlogPhoenix.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /graphiql
** (exit) an exception was raised:
    ** (Mssqlex.Error) [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'id'. | ODBC_CODE 42S22 | SQL_SERVER_CODE 207
        (ecto) lib/ecto/adapters/sql.ex:436: Ecto.Adapters.SQL.execute_and_cache/7
```

**Comment by ssomnoremac** [comment]
Ah, I have to define the primary key!
```
  @primary_key {:sm_id, :integer, []}
  schema "Profile" do
    field :first_name, :string
  end
```

**Comment by benwilson512** [comment]
I'm glad you got this sorted out but I'm not really sure I understand the question, and I want to make sure that you don't have any misconceptions about how Absinthe works. There is no automatic mapping of graphql object fields to your db schema columns. If you look up a profile in the `profile` field it's gonna by default just do the normal ecto lookup which will get all the ecto schema fields you specify.

I'm not sure why you didn't end up with a normal id primary key. Do note that in your fork of this example you committed a TON of beam files, which is not really something you want to do.

**Comment by ssomnoremac** [comment]
Hey Ben, thanks for getting back and for all your work on this. I'm aware that I committed all those files, I will delete the repo and repost with the proper gitignore. 

> I'm not sure why you didn't end up with a normal id primary key

That's because I'm looking at my existing database and not a phoenix generated one. Sorry I didn't make that clear.  I'm aware there's no automatic mapping too. What would be nice is the automatic batching based on ecto schema as described in the [Best Practices](http://absinthe-graphql.org/guides/ecto-best-practices/) section of the docs. Do you know of any work being done on this?

**Comment by benwilson512** [comment]
That guide needs to be updated, https://hexdocs.pm/absinthe_ecto/Absinthe.Ecto.html contains the assoc helper mentioned there.

**Comment by ssomnoremac** [comment]
awesome! Thanks. Can't wait to read that book btw!
