### ISSUE TITLE
How to write scalar for location and datetime?

### ISSUE THREAD

**Issue by karthikeyan234** [absinthe-graphql/absinthe_example#15]
In location we will be storing { longitude , latirude }.I am using posgresql DB.Any example queries will be more useful too.Thanks:-)

**Comment by benwilson512** [comment]
What have you tried so far?

**Comment by karthikeyan234** [comment]
I tried :location and some other choices from different links but none working

 mix phx.gen.schema Location location name:string loc:location

 it is throwing error.Your help will be greatly appreciated.Thanks:-)

**Comment by benwilson512** [comment]
Is it the Phoenix generator you're having trouble with? Because those have nothing to do with absinthe.

**Comment by karthikeyan234** [comment]
We are using this library
https://github.com/bryanjos/geo/tree/351ee6c4f8ed24541c9c2908f615e7b0a238f010

For ex Below are my sample module and table

Module :
  defmodule Geographies do
    use Ecto.Model

    schema "geographies" do
      field :name,           :string
      field :geom,           Geo.Point
    end
  end


Table :

  create table(:geographies) do
    add :name,     :string
    add :geom,     :geometry
  end


Sample Queries like

defmodule Example do
  import Ecto.Query
  import Geo.PostGIS

  def example_query(geom) do
    from geom in geographies, limit: 5, select: st_distance(location.geom, ^geom) ///somewhat similar to this one
  end

end




Now how i need to create scalar for this

object :item do
  @desc "The item's name"
  field :name, :string,

  field :geom, :   //WHAT TYPE I MUST USE HERE
end


SAMPLE INSERT ;
INSERT INTO geographies(name, geom)
VALUES('david', ST_GeomFromText('POINT(-71.060316 48.432044)', 4326));

**Comment by bruce** [comment]
@karthikeyan234 For example, if you're using an input string format that `Geo.WKT.decode/1` can handle (eg, `"SRID=4326;POINT(30 -90)"`), something like this will probably work:

```elixir
scalar :geo_point do
  parse fn
    %Absinthe.Blueprint.Input.String{value: raw} ->
      {:ok, Geo.WKT.decode(raw)}
    _ ->
      :error
  end
  serialize &Geo.WKT.encode/1
end
```

You may want to wrap the use of `Geo.WKT.decode/1` in a `try` block if it raises on bad input (it doesn't appear, based on the docs, to return a conventional `{:ok | :error, term}` tuple).
