### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by noma4i** [absinthe-graphql/absinthe_example#4]
```
undefined function nil.variable_definitions/0
```

**Comment by scottschulthess** [comment]
Full stack trace ``` absinthe_example git:(master) ✗ PORT=4001 mix phoenix.server
[info] Running Blog.Endpoint with Cowboy using http on port 4001
[info] GET /api
[debug] GraphQL Document:


[info] Sent 500 in 143ms
[error] #PID<0.308.0> running Blog.Endpoint terminated
Server: localhost:4001 (http)
Request: GET /api
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function nil.variable_definitions/0
        nil.variable_definitions()
        (absinthe) Absinthe.Execution.Variables.build/1
        (absinthe) lib/absinthe/execution.ex:176: Absinthe.Execution.set_variables/1
        (absinthe) lib/absinthe/execution.ex:29: Absinthe.Execution.run/2
        (absinthe) lib/absinthe.ex:232: Absinthe.run/3
        (absinthe_plug) lib/absinthe/plug.ex:78: Absinthe.Plug.do_call/5
        (phoenix) lib/phoenix/router/route.ex:157: Phoenix.Router.Route.forward/4
        (blog) lib/phoenix/router.ex:261: Blog.Router.dispatch/2
        (blog) web/router.ex:1: Blog.Router.do_call/2
        (blog) lib/blog/endpoint.ex:1: Blog.Endpoint.phoenix_pipeline/1
        (blog) lib/plug/debugger.ex:93: Blog.Endpoint."call (overridable 3)"/2
        (blog) lib/phoenix/endpoint/render_errors.ex:34: Blog.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
^A[```

**Comment by superchris** [comment]
I got it working, altho with not quite all of the original features: #5
