### ISSUE TITLE
new version for phoenix 1.3?

### ISSUE THREAD

**Issue by zeroasterisk** [absinthe-graphql/absinthe_example#8]
Are you planning on restructuring this to better match the new paths for phoenix 1.3?

Perhaps generate a new phx project and "update" it with absinthe?

_(thanks!!!)_

**Comment by bruce** [comment]
We did eventually get to this... The new tutorial content is up in the [v1.4 hexdocs](https://hexdocs.pm/absinthe/1.4.0-rc.3/overview.html) and the new tutorial code is in absinthe_tutorial. (This example code repo will be removed once v1.4 hits stable in couple days.)
