### ISSUE TITLE
More guides for noobs

### ISSUE THREAD

**Issue by zeroasterisk** [absinthe-graphql/absinthe_example#9]
I'm somewhat familiar with graphql, phoenix, and elixir - but new to all of them.

Your guides are great, but I'd like a bit more guidance on things like:
- how best to organize a set of more complex schemas for different types of objects and queries
- how best to coordinate graphql schemas and ecto schemas (you have a section on this, but I'm still not sure I understand)
- an example of using multiple graphql scoped endpoints through routes + pipelines

Anyway - I'm excited and will be digging in - just letting you know what I'm wishing for.

**Comment by benwilson512** [comment]
Hey! Yeah we are keenly aware of this need. Part of the challenge at the moment is that a lot of effort is being channeled into the Absinthe book we're writing for Prag Prog, which makes it difficult to slot in time for guide upgrades.

There have been some good blog posts from third parties, I'll try to link them here in the morning.

**Comment by zeroasterisk** [comment]
this book? https://www.amazon.com/Craft-GraphQL-APIs-Elixir-Absinthe/dp/1680502557/
